kind: Pod
apiVersion: v1
metadata:
  name: artifactory-retention
  namespace: cicd
  labels:
    app: artifactory-retention
spec:
  containers:
    - name: artifactory-retention
      image: azweb76/artifactory-retention
      imagePullPolicy: Always
      env:
        - name: ART_URL
          value: https://artifactory.mydomain.com/artifactory
        - name: ART_USER
          valueFrom:
            secretKeyRef:
              name: artifactory-user
              key: artifactory-username
        - name: ART_PASSWORD
          valueFrom:
            secretKeyRef:
              name: artifactory-user
              key: artifactory-password
      command:
        - artret
        - --repo
        - docker-my-local
        - clean
        - --days
        - '10'
        - --interval
        - '86400'
